# Generated by Django 4.1.2 on 2022-12-20 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=30)),
                ('description_of_book', models.TextField()),
                ('image_of_book', models.ImageField(upload_to='')),
                ('author_of_book', models.CharField(max_length=50)),
                ('short_description_of_book', models.TextField(max_length=100)),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100)),
                ('download', models.FileField(blank=True, help_text='download only PDF', null=True, upload_to=users.models.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Model_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=500)),
                ('sponsors', models.CharField(max_length=500)),
                ('friends', models.CharField(max_length=500)),
                ('authors', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Model_notes_of_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_note', models.CharField(max_length=200)),
                ('text_note', models.TextField()),
                ('date_note', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
